POST localhost:8080/books/addbook/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQG1haWwucnUiLCJSb2xlIjoiYWRtaW4ifQ.96wwenDmcHc-IgNAI-hDOWtmd5ya74pHfgbjgyF2j7Q
Content-Type: application/json

{
"name": "Хорошая книга 3",
"author": "Я2222",
"yearOfProduction": 2021,
"annotation": "читать по любому"
}


###

POST localhost:8080/books/addbook/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InVzZXIxQG1haWwucnUiLCJSb2xlIjoidXNlciJ9.zczbu6YPC1hHaH_ZUIplkvNpZ3u0hpV3cxsbaPYmbYY
Content-Type: application/json

{
  "name": "Хорошая книга 3",
  "author": "Я2222",
  "yearOfProduction": 2021,
  "annotation": "читать по любому"
}
