### редакт админ
POST localhost:8080/persons/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQG1haWwucnUiLCJSb2xlIjoiYWRtaW4iLCJOYW1lIjoiQW50b24iLCJJZCI6NDl9.V0u-QTc214holH8qEPyQJx8Qp9nFtMNMMhCuUepQBlI
Content-Type: application/json

{
  "id": 23,
  "name": "Федор",
  "age": 31,
  "email": "user1@mail.ru",
  "phoneNumber": "+7 933 3323333",
  "password" : "12345",
  "role": "admin"
}


### редакт не админ
POST localhost:8080/persons/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InVzZXI1QG1haWwucnUiLCJSb2xlIjoidXNlciIsIk5hbWUiOiJ1c2VyNSIsIklkIjo1MH0._itNmFAn2HLtAgyLuOpHlIAqS2Z_G5HeFekKiEI4d1Y
Content-Type: application/json

{
  "id": 23,
  "name": "Федор",
  "age": 33,
  "email": "user1@mail.ru",
  "phoneNumber": "+7 933 3323333",
  "password" : "12345",
  "role": "admin"
}

