GET localhost:8080/auth/get-token
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "2222"
}


###

GET localhost:8080/auth/get-token
Content-Type: application/json

{
  "email": "user1@mail.ru",
  "password": "2222"
}