POST localhost:8080/persons/reg/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQG1haWwucnUiLCJSb2xlIjoiYWRtaW4ifQ.96wwenDmcHc-IgNAI-hDOWtmd5ya74pHfgbjgyF2j7Q
Content-Type: application/json

{
  "name": "user1",
  "email": "user1@mail.ru",
  "role": "user",
  "password" : "2222"
}