### рег админ
POST localhost:8080/persons/reg/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQG1haWwucnUiLCJSb2xlIjoiYWRtaW4iLCJOYW1lIjoiQW50b24ifQ.MbDFDri66C9QOj0TPpDcHdeGjAu-fPgurk6uezPMlAM
Content-Type: application/json

{
  "name": "user4",
  "email": "user4@mail.ru",
  "password" : "2222"
}


### рег не админ
POST localhost:8080/persons/reg/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InVzZXIyQG1haWwucnUiLCJSb2xlIjoidXNlciIsIk5hbWUiOiJ1c2VyMSJ9.22gf5yQPz2sYf4Tpjm-oK26qYwaoBEcrjNEebTbD05o
Content-Type: application/json

{
  "name": "user2",
  "email": "user1@mail.ru",
  "password" : "2222"
}
